name: CI # Name of our workflow

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest # Environment job will run in

    steps: # Each action/command to run
    - uses: actions/checkout@v2 # Helps check out the repo code
    - run: npm install node-fetch --save
    - uses: ./.github/actions/test-action # Tell it to run out JS Action
    - name: Commit Files
      run: |
        git config --global user.name 'Saket Kumar'
        git config --global user.email 'saket1999@users.noreply.github.com'
        git commit -am "Updating new data"
        git push
