name: Update Data # Name of our workflow

on: 
  schedule:
  - cron: "0 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest # Environment job will run in

    steps: # Each action/command to run
    - uses: actions/checkout@v2 # Helps check out the repo code
    - run: npm install node-fetch --save
    - uses: ./.github/actions/test-action # Tell it to run out JS Action
    - name: Commit Files
      run: |
        git config --global user.name 'Saket Kumar'
        git config --global user.email 'saket1999@users.noreply.github.com'
        git add data.json
        git commit -am "Updated `date +'%Y-%m-%d %H:%M:%S'`" || echo "No changes to commit"
        git push
